### ISSUE TITLE
配置文件扩展名不统一

### ISSUE THREAD

**Issue by arrebole** [geektheripper/super-cp#1]
## 问题:
配置文件名扩展存在冲突
+ [example.yml](https://github.com/geektheripper/super-cp/blob/master/example.yml) 配置文件扩展名为 `.yml`
+ [README](https://github.com/geektheripper/super-cp/blob/master/README.md) 中的描述配置文件扩展名为 `example.yaml` 

## 建议：
+ 统一使用 `yaml` 作为扩展名

## 参考
+ [yml和yaml的区别](https://stackoverflow.com/questions/22268952/what-is-the-difference-between-yaml-and-yml-extension)

**Comment by geektheripper** [comment]
done in: d50e90923de4f5d19c3bcf280935fa5ac19402b7
